"""
Script builder for generating reproducible Python analysis scripts.
Supports both pyDESeq2 and edgePython differential expression tools.
"""

from datetime import datetime
from typing import Dict, List, Optional
from jinja2 import Template


class ScriptBuilder:
    """
    Generates reproducible Python scripts from analysis parameters.
    Adapts code generation based on the active differential testing tool.
    """

    def __init__(
        self,
        analysis_params: Optional[Dict] = None,
        selected_genes: Optional[List[str]] = None,
        active_tool: str = 'pydeseq2',
    ):
        self.analysis_params = analysis_params or {
            'condition_column': 'condition',
            'reference_level': 'control',
            'lfc_threshold': 1.0,
            'padj_threshold': 0.05
        }
        self.selected_genes = selected_genes or []
        self.active_tool = active_tool  # 'pydeseq2' or 'edgepython'
        self.data_paths = {
            'counts': 'counts.csv',
            'metadata': 'metadata.csv'
        }

    @property
    def tool_display_name(self) -> str:
        return 'pyDESeq2' if self.active_tool == 'pydeseq2' else 'edgePython'

    @property
    def results_filename(self) -> str:
        return 'deseq2_results.csv' if self.active_tool == 'pydeseq2' else 'edgepython_results.csv'

    def set_data_paths(self, counts_path: str, metadata_path: str):
        """Set paths for data files."""
        self.data_paths['counts'] = counts_path
        self.data_paths['metadata'] = metadata_path

    def generate_script(self, include_sections: Dict[str, bool]) -> str:
        """
        Generate complete Python script.

        Parameters
        ----------
        include_sections : dict
            Which sections to include:
            - data_loading: bool
            - deseq2: bool  (now means "differential expression" regardless of tool)
            - volcano: bool
            - boxplot: bool
            - heatmap: bool
            - gsea: bool

        Returns
        -------
        str
            Complete Python script
        """
        sections = []

        # Header
        sections.append(self._generate_header())

        # Imports
        sections.append(self._generate_imports(include_sections))

        # Data loading
        if include_sections.get('data_loading', True):
            sections.append(self._generate_data_loading())

        # Differential expression analysis
        if include_sections.get('deseq2', True):
            if self.active_tool == 'edgepython':
                sections.append(self._generate_edgepython_analysis())
            else:
                sections.append(self._generate_deseq_analysis())

        # Volcano plot
        if include_sections.get('volcano', False):
            sections.append(self._generate_volcano_code())

        # Boxplot
        if include_sections.get('boxplot', False) and self.selected_genes:
            sections.append(self._generate_boxplot_code())

        # Heatmap
        if include_sections.get('heatmap', False):
            sections.append(self._generate_heatmap_code())

        # GSEA
        if include_sections.get('gsea', False):
            sections.append(self._generate_gsea_code())

        # Footer
        sections.append(self._generate_footer())

        return '\n\n'.join(filter(None, sections))

    def _generate_header(self) -> str:
        """Generate script header."""
        return f'''"""
RNA-seq Differential Expression Analysis Script
===============================================
Generated by RNA-seq Differential Analyzer
Tool: {self.tool_display_name}
Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

This script reproduces the analysis performed in the GUI application.
Run this script to regenerate all figures and results.
"""'''

    def _generate_imports(self, include_sections: Dict[str, bool]) -> str:
        """Generate import statements."""
        imports = [
            "import pandas as pd",
            "import numpy as np",
            "import matplotlib.pyplot as plt"
        ]

        if any([include_sections.get('volcano'), include_sections.get('boxplot'),
                include_sections.get('heatmap')]):
            imports.append("import seaborn as sns")

        if include_sections.get('deseq2', True):
            if self.active_tool == 'edgepython':
                imports.append("import edgepython as ep")
            else:
                imports.extend([
                    "from pydeseq2.dds import DeseqDataSet",
                    "from pydeseq2.ds import DeseqStats",
                    "from pydeseq2.default_inference import DefaultInference"
                ])

        if include_sections.get('heatmap'):
            imports.extend([
                "from scipy.cluster.hierarchy import linkage, leaves_list",
                "from scipy.spatial.distance import pdist"
            ])

        if include_sections.get('gsea'):
            imports.append("import gseapy as gp")

        imports.append("")
        imports.append("# Set plot style")
        imports.append("plt.style.use('seaborn-v0_8-whitegrid')")
        imports.append("plt.rcParams['figure.dpi'] = 150")
        imports.append("plt.rcParams['savefig.dpi'] = 300")

        return '\n'.join(imports)

    def _generate_data_loading(self) -> str:
        """Generate data loading code."""
        return f'''
# =============================================================================
# Data Loading
# =============================================================================

# Load count matrix (genes as rows, samples as columns)
counts = pd.read_csv("{self.data_paths['counts']}", index_col=0)

# Load sample metadata
metadata = pd.read_csv("{self.data_paths['metadata']}", index_col=0)

# Verify sample alignment
common_samples = list(set(counts.columns) & set(metadata.index))
counts = counts[common_samples]
metadata = metadata.loc[common_samples]

print(f"Loaded {{counts.shape[0]}} genes x {{counts.shape[1]}} samples")
print(f"Conditions: {{metadata['{self.analysis_params['condition_column']}'].value_counts().to_dict()}}")'''

    def _generate_deseq_analysis(self) -> str:
        """Generate pyDESeq2 analysis code."""
        return f'''
# =============================================================================
# Differential Expression Analysis (pyDESeq2)
# =============================================================================

# Analysis parameters
CONDITION_COLUMN = "{self.analysis_params['condition_column']}"
REFERENCE_LEVEL = "{self.analysis_params['reference_level']}"
LFC_THRESHOLD = {self.analysis_params['lfc_threshold']}
PADJ_THRESHOLD = {self.analysis_params['padj_threshold']}

# Create inference object
inference = DefaultInference(n_cpus=4)

# Create DESeq2 dataset
# Note: PyDESeq2 expects samples as rows, genes as columns
dds = DeseqDataSet(
    counts=counts.T,
    metadata=metadata,
    design_factors=CONDITION_COLUMN,
    refit_cooks=True,
    inference=inference,
    ref_level=[CONDITION_COLUMN, REFERENCE_LEVEL]
)

# Run DESeq2 pipeline
print("Running pyDESeq2 analysis...")
dds.deseq2()

# Statistical testing
stats = DeseqStats(dds, inference=inference)
stats.summary()

# Get results
results = stats.results_df.copy()

# Add significance annotations
results['significant'] = (results['padj'] < PADJ_THRESHOLD) & \\
                         (np.abs(results['log2FoldChange']) > LFC_THRESHOLD)
results['direction'] = np.where(results['log2FoldChange'] > 0, 'up', 'down')

# Get normalized counts
normalized_counts = pd.DataFrame(
    dds.layers['normed_counts'],
    index=dds.obs_names,
    columns=dds.var_names
)

# Summary
n_sig = results['significant'].sum()
n_up = ((results['significant']) & (results['direction'] == 'up')).sum()
n_down = ((results['significant']) & (results['direction'] == 'down')).sum()

print(f"\\nSignificant genes: {{n_sig}}")
print(f"  Upregulated: {{n_up}}")
print(f"  Downregulated: {{n_down}}")

# Save results
results.to_csv("{self.results_filename}")
print(f"\\nResults saved to {self.results_filename}")'''

    def _generate_edgepython_analysis(self) -> str:
        """Generate edgePython analysis code."""
        normalization = self.analysis_params.get('normalization', 'TMM')
        test_method = self.analysis_params.get('test_method', 'qlf')
        robust_raw = self.analysis_params.get('robust', True)
        # Normalize JS boolean strings to Python bool
        if isinstance(robust_raw, str):
            robust = robust_raw.lower() in ('true', '1', 'yes')
        else:
            robust = bool(robust_raw)
        min_count = int(self.analysis_params.get('min_count', 10))

        test_label = 'Quasi-likelihood F-test' if test_method == 'qlf' else 'Exact test'

        return f'''
# =============================================================================
# Differential Expression Analysis (edgePython)
# =============================================================================
# edgePython: Python implementation of edgeR by Lior Pachter's lab
# https://github.com/pachterlab/edgePython

# Analysis parameters
CONDITION_COLUMN = "{self.analysis_params['condition_column']}"
REFERENCE_LEVEL = "{self.analysis_params['reference_level']}"
LFC_THRESHOLD = {self.analysis_params['lfc_threshold']}
PADJ_THRESHOLD = {self.analysis_params['padj_threshold']}

# edgePython-specific parameters
NORMALIZATION = "{normalization}"        # TMM, TMMwsp, RLE, upperquartile, none
TEST_METHOD = "{test_method}"            # qlf ({test_label}) or exact (Exact test)
ROBUST = {robust}                        # Robust fitting for GLM
MIN_COUNT = {min_count}                  # Minimum total count to keep a gene

# Get group labels
groups = metadata[CONDITION_COLUMN].values
unique_groups = list(pd.unique(groups))

# Set reference level
if REFERENCE_LEVEL in unique_groups:
    unique_groups.remove(REFERENCE_LEVEL)
    unique_groups.insert(0, REFERENCE_LEVEL)

# Encode groups numerically for design matrix
group_numeric = np.array([unique_groups.index(g) for g in groups], dtype=float)

# Filter low-count genes
if MIN_COUNT > 0:
    keep = counts.sum(axis=1) >= MIN_COUNT
    counts_filtered = counts[keep]
    print(f"Filtered from {{counts.shape[0]}} to {{counts_filtered.shape[0]}} genes (min count = {{MIN_COUNT}})")
else:
    counts_filtered = counts

# Convert to numpy
counts_np = counts_filtered.values.astype(float)
gene_names = list(counts_filtered.index)

# Create DGEList
print("Running edgePython analysis...")
y = ep.make_dgelist(counts=counts_np, group=group_numeric)

# Normalize
if NORMALIZATION != "none":
    y = ep.calc_norm_factors(y, method=NORMALIZATION)
    print(f"Applied {{NORMALIZATION}} normalization")

# Estimate dispersion
y = ep.estimate_disp(y)

n_samples = len(groups)

if TEST_METHOD == "exact":
    # Exact test (two-group comparison)
    test_result = ep.exact_test(y)
    top = ep.top_tags(test_result, n=len(gene_names))
    print("Used Exact test for two-group comparison")
else:
    # Quasi-likelihood F-test with design matrix
    design = np.column_stack([
        np.ones(n_samples),
        group_numeric,
    ])
    fit = ep.glm_ql_fit(y, design, robust=ROBUST)
    test_result = ep.glm_ql_ftest(fit, coef=1)
    top = ep.top_tags(test_result, n=len(gene_names))
    print(f"Used QL F-test (robust={{ROBUST}})")

# Extract results table
res_table = top['table']

# Map back to gene names
if len(res_table) <= len(gene_names):
    res_table.index = [gene_names[i] if i < len(gene_names) else f'gene_{{i}}'
                       for i in res_table.index]

# Standardize column names (compatible with downstream plots)
results = pd.DataFrame(index=res_table.index)
results['baseMean'] = counts_filtered.loc[results.index].mean(axis=1)
results['log2FoldChange'] = res_table['logFC'].values if 'logFC' in res_table.columns else 0.0
results['lfcSE'] = np.abs(results['log2FoldChange']) / 2.0  # approximate
results['pvalue'] = res_table['PValue'].values if 'PValue' in res_table.columns else 1.0
results['padj'] = res_table['FDR'].values if 'FDR' in res_table.columns else results['pvalue']

# Add significance annotations
results['significant'] = (results['padj'] < PADJ_THRESHOLD) & \\
                         (np.abs(results['log2FoldChange']) > LFC_THRESHOLD)
results['direction'] = np.where(results['log2FoldChange'] > 0, 'up', 'down')

# CPM-normalized counts for downstream plots
lib_sizes = counts_filtered.sum(axis=0)
normalized_counts = (counts_filtered.div(lib_sizes, axis=1) * 1e6).T  # samples x genes

# Summary
n_sig = results['significant'].sum()
n_up = ((results['significant']) & (results['direction'] == 'up')).sum()
n_down = ((results['significant']) & (results['direction'] == 'down')).sum()

print(f"\\nSignificant genes: {{n_sig}}")
print(f"  Upregulated: {{n_up}}")
print(f"  Downregulated: {{n_down}}")

# Save results
results.to_csv("{self.results_filename}")
print(f"\\nResults saved to {self.results_filename}")'''

    def _generate_volcano_code(self) -> str:
        """Generate volcano plot code."""
        selected_str = repr(self.selected_genes) if self.selected_genes else "[]"

        return f'''
# =============================================================================
# Volcano Plot
# =============================================================================

def create_volcano_plot(results, lfc_thresh, pval_thresh, highlight_genes=None):
    """Create publication-ready volcano plot."""
    fig, ax = plt.subplots(figsize=(10, 8))

    # Prepare data
    df = results.dropna(subset=['log2FoldChange', 'padj']).copy()
    df['neg_log10_padj'] = -np.log10(df['padj'].replace(0, 1e-300))

    # Categorize genes
    up = (df['log2FoldChange'] >= lfc_thresh) & (df['padj'] < pval_thresh)
    down = (df['log2FoldChange'] <= -lfc_thresh) & (df['padj'] < pval_thresh)
    ns = ~(up | down)

    # Plot
    ax.scatter(df.loc[ns, 'log2FoldChange'], df.loc[ns, 'neg_log10_padj'],
               c='#CCCCCC', alpha=0.5, s=20, label='NS', rasterized=True)
    ax.scatter(df.loc[up, 'log2FoldChange'], df.loc[up, 'neg_log10_padj'],
               c='#E74C3C', alpha=0.7, s=30, label=f'Up ({{up.sum()}})')
    ax.scatter(df.loc[down, 'log2FoldChange'], df.loc[down, 'neg_log10_padj'],
               c='#3498DB', alpha=0.7, s=30, label=f'Down ({{down.sum()}})')

    # Threshold lines
    ax.axhline(-np.log10(pval_thresh), color='gray', linestyle='--', alpha=0.5, linewidth=1)
    ax.axvline(lfc_thresh, color='gray', linestyle='--', alpha=0.5, linewidth=1)
    ax.axvline(-lfc_thresh, color='gray', linestyle='--', alpha=0.5, linewidth=1)

    # Highlight selected genes
    if highlight_genes:
        for gene in highlight_genes:
            if gene in df.index:
                x = df.loc[gene, 'log2FoldChange']
                y = df.loc[gene, 'neg_log10_padj']
                ax.annotate(gene, xy=(x, y), xytext=(5, 5), textcoords='offset points',
                           fontsize=8, fontweight='bold',
                           bbox=dict(boxstyle='round,pad=0.3', facecolor='yellow', alpha=0.7))

    # Styling
    ax.set_xlabel('Log$_2$ Fold Change', fontsize=12)
    ax.set_ylabel('-Log$_{{10}}$ Adjusted P-value', fontsize=12)
    ax.set_title('Volcano Plot ({self.tool_display_name})', fontsize=14, fontweight='bold')
    ax.legend(loc='upper right', frameon=True)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    plt.tight_layout()
    return fig, ax

# Create volcano plot
highlight_genes = {selected_str}
fig_volcano, _ = create_volcano_plot(results, LFC_THRESHOLD, PADJ_THRESHOLD, highlight_genes)
fig_volcano.savefig('volcano_plot.png', dpi=300, bbox_inches='tight')
plt.show()
print("Volcano plot saved to volcano_plot.png")'''

    def _generate_boxplot_code(self) -> str:
        """Generate boxplot code."""
        selected_str = repr(self.selected_genes)

        return f'''
# =============================================================================
# Gene Expression Boxplots
# =============================================================================

def create_boxplots(normalized_counts, metadata, genes, group_col, results,
                    normalization='log2'):
    """Create grouped boxplots with significance stars."""
    if not genes:
        print("No genes selected for boxplot")
        return None, None

    # Prepare data
    valid_genes = [g for g in genes if g in normalized_counts.columns]
    expr = normalized_counts[valid_genes].copy()

    if normalization == 'log2':
        expr = np.log2(expr + 1)
        ylabel = 'Log$_2$(Normalized Counts + 1)'
    else:
        ylabel = 'Normalized Counts'

    # Melt for seaborn
    expr['sample'] = expr.index
    expr = expr.merge(metadata[[group_col]], left_on='sample', right_index=True)
    plot_data = expr.melt(id_vars=['sample', group_col], var_name='gene', value_name='expression')

    # Create plot
    fig, ax = plt.subplots(figsize=(max(8, len(valid_genes) * 1.5), 6))

    # Boxplot with points
    palette = {{'control': '#3498DB', 'treatment': '#E74C3C'}}
    sns.boxplot(data=plot_data, x='gene', y='expression', hue=group_col,
                ax=ax, palette=palette, width=0.6)
    sns.stripplot(data=plot_data, x='gene', y='expression', hue=group_col,
                  ax=ax, dodge=True, alpha=0.6, size=4, legend=False)

    # Add significance stars
    def pvalue_to_stars(pval):
        if pd.isna(pval): return ''
        if pval < 0.001: return '***'
        if pval < 0.01: return '**'
        if pval < 0.05: return '*'
        return 'ns'

    for i, gene in enumerate(valid_genes):
        if gene in results.index:
            padj = results.loc[gene, 'padj']
            stars = pvalue_to_stars(padj)
            if stars:
                ymax = ax.get_ylim()[1]
                ax.text(i, ymax * 0.95, stars, ha='center', va='bottom',
                       fontsize=12, fontweight='bold')

    # Styling
    ax.set_xlabel('Gene', fontsize=12)
    ax.set_ylabel(ylabel, fontsize=12)
    ax.set_title('Gene Expression by Condition', fontsize=14, fontweight='bold')
    ax.legend(title=group_col.capitalize(), loc='upper right')
    plt.xticks(rotation=45, ha='right')
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    plt.tight_layout()
    return fig, ax

# Create boxplots for selected genes
selected_genes = {selected_str}
fig_box, _ = create_boxplots(normalized_counts, metadata, selected_genes,
                              CONDITION_COLUMN, results, normalization='log2')
if fig_box:
    fig_box.savefig('boxplots.png', dpi=300, bbox_inches='tight')
    plt.show()
    print("Boxplots saved to boxplots.png")'''

    def _generate_heatmap_code(self) -> str:
        """Generate heatmap code."""
        return f'''
# =============================================================================
# Expression Heatmap
# =============================================================================

def create_heatmap(normalized_counts, metadata, results, top_n=50,
                   annotation_cols=['condition'], scale='row'):
    """Create clustered heatmap with metadata annotations."""
    # Select top variable genes
    gene_var = normalized_counts.var()
    top_genes = gene_var.nlargest(top_n).index.tolist()

    # Get expression data
    expr = normalized_counts[top_genes].copy()
    expr = np.log2(expr + 1)

    # Scale
    if scale == 'row':
        expr = expr.apply(lambda x: (x - x.mean()) / x.std() if x.std() > 0 else x, axis=0)

    # Cluster
    try:
        sample_dist = pdist(expr.values)
        sample_linkage = linkage(sample_dist, method='average')
        sample_order = leaves_list(sample_linkage)

        gene_dist = pdist(expr.values.T)
        gene_linkage = linkage(gene_dist, method='average')
        gene_order = leaves_list(gene_linkage)

        expr = expr.iloc[sample_order, gene_order]
    except:
        pass

    # Create annotation colors
    row_colors = None
    if annotation_cols:
        color_maps = {{
            'condition': {{'control': '#3498DB', 'treatment': '#E74C3C'}},
            'batch': {{'batch1': '#2ECC71', 'batch2': '#9B59B6'}},
            'sex': {{'M': '#3498DB', 'F': '#E91E63'}}
        }}
        row_colors = pd.DataFrame(index=expr.index)
        for col in annotation_cols:
            if col in metadata.columns:
                colors = color_maps.get(col, {{}})
                if not colors:
                    unique_vals = metadata[col].unique()
                    palette = sns.color_palette('husl', len(unique_vals))
                    colors = dict(zip(unique_vals, palette))
                row_colors[col] = metadata.loc[expr.index, col].map(colors)

    # Create clustermap
    g = sns.clustermap(
        expr.T,
        cmap='RdBu_r',
        figsize=(12, 10),
        row_cluster=True,
        col_cluster=True,
        col_colors=row_colors,
        linewidths=0,
        xticklabels=True,
        yticklabels=True,
        cbar_pos=(0.02, 0.8, 0.03, 0.15)
    )

    g.ax_heatmap.set_xlabel('Samples', fontsize=12)
    g.ax_heatmap.set_ylabel('Genes', fontsize=12)
    plt.setp(g.ax_heatmap.xaxis.get_majorticklabels(), rotation=45, ha='right', fontsize=8)
    plt.setp(g.ax_heatmap.yaxis.get_majorticklabels(), fontsize=8)

    return g

# Create heatmap
g_heatmap = create_heatmap(normalized_counts, metadata, results, top_n=50,
                            annotation_cols=['{self.analysis_params['condition_column']}'])
g_heatmap.savefig('heatmap.png', dpi=300, bbox_inches='tight')
plt.show()
print("Heatmap saved to heatmap.png")'''

    def _generate_gsea_code(self) -> str:
        """Generate GSEA code."""
        return f'''
# =============================================================================
# Pathway Analysis (GSEA)
# =============================================================================

def run_gsea_analysis(results, gene_sets='KEGG_2021_Human'):
    """Run prerank GSEA analysis."""
    # Create ranking metric
    df = results.dropna(subset=['pvalue', 'log2FoldChange']).copy()
    pvals = df['pvalue'].replace(0, 1e-300)
    ranking = -np.log10(pvals) * np.sign(df['log2FoldChange'])
    ranking = ranking.sort_values(ascending=False)

    # Create ranking DataFrame
    rnk = ranking.reset_index()
    rnk.columns = ['gene', 'rank']
    rnk['gene'] = rnk['gene'].str.upper()

    # Run GSEA
    print(f"Running GSEA with {{gene_sets}}...")
    gsea_results = gp.prerank(
        rnk=rnk,
        gene_sets=gene_sets,
        min_size=15,
        max_size=500,
        permutation_num=1000,
        seed=42,
        outdir=None,
        verbose=True
    )

    return gsea_results.res2d

# Run GSEA
gsea_results = run_gsea_analysis(results, gene_sets='KEGG_2021_Human')

# Display top results
print("\\nTop enriched pathways:")
print(gsea_results.head(10)[['Term', 'NES', 'NOM p-val', 'FDR q-val']])

# Save results
gsea_results.to_csv('gsea_results.csv', index=False)
print("\\nGSEA results saved to gsea_results.csv")

# Create enrichment dot plot
def create_gsea_dotplot(gsea_results, top_n=15):
    """Create GSEA enrichment dot plot."""
    df = gsea_results.head(top_n).copy()

    fig, ax = plt.subplots(figsize=(10, 8))

    # Color by NES (positive = red, negative = blue)
    colors = ['#E74C3C' if x > 0 else '#3498DB' for x in df['NES']]

    # Size by -log10(FDR)
    sizes = -np.log10(df['FDR q-val'].replace(0, 1e-10)) * 20

    scatter = ax.scatter(df['NES'], range(len(df)), c=colors, s=sizes, alpha=0.7)

    ax.set_yticks(range(len(df)))
    ax.set_yticklabels(df['Term'])
    ax.set_xlabel('Normalized Enrichment Score (NES)', fontsize=12)
    ax.set_title('GSEA Enrichment Results', fontsize=14, fontweight='bold')
    ax.axvline(0, color='gray', linestyle='--', alpha=0.5)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    plt.tight_layout()
    return fig, ax

if len(gsea_results) > 0:
    fig_gsea, _ = create_gsea_dotplot(gsea_results)
    fig_gsea.savefig('gsea_dotplot.png', dpi=300, bbox_inches='tight')
    plt.show()
    print("GSEA dot plot saved to gsea_dotplot.png")'''

    def _generate_footer(self) -> str:
        """Generate script footer."""
        results_file = self.results_filename
        return f'''
# =============================================================================
# Script Complete
# =============================================================================

print("\\n" + "="*50)
print("Analysis complete! (Tool: {self.tool_display_name})")
print("="*50)
print("\\nGenerated files:")
print("  - {results_file}: Differential expression results")
print("  - volcano_plot.png: Volcano plot")
print("  - boxplots.png: Gene expression boxplots")
print("  - heatmap.png: Expression heatmap")
print("  - gsea_results.csv: Pathway analysis results")
print("  - gsea_dotplot.png: GSEA enrichment plot")'''
